### ISSUE TITLE
Setting current directory for find seems to have no effect

### ISSUE THREAD

**Issue by ddssff** [bos/filemanip#16]
I would expect the ls and find below to output more or less the same list of files, but the find somehow doesn't notice the change of current directory:

```
> :m +Control.Exception System.Directory System.Process System.FilePath.Find
> let withCurrentDirectory dir action = bracket getCurrentDirectory setCurrentDirectory $ \ _ -> setCurrentDirectory dir >> action
> withCurrentDirectory "/tmp" (readProcess "ls" [] "")
> withCurrentDirectory "/tmp" (find (depth <=? 1) always ".")
```

**Comment by ddssff** [comment]
Bryan - are you off the grid?  I can't see you anywhere.

**Comment by jaspervdj** [comment]
@ddssff The problem here is that `find` produces a lazy list.  The directory is changed back before the entire list is created.  You can fix that by doing something like this:

```
files <- withCurrentDirectory dir $ do
    matches <- find (depth <=? 1) always "."
    length matches `seq` return matches
```
